version: "3.0"
services:
    user:
        build:
            context: ..
            dockerfile: build/package/user.Dockerfile
        ports:
            - "8080:8080"
        environment:
            MONGODB_URI: mongodb://root:example@mongo:27017/test?authSource=admin
        depends_on:
            - "mongo"
    mongo:
        image: mongo:6.0-focal
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: test
    e2e:
        build:
            context: ..
            dockerfile: build/test/e2e.Dockerfile
        environment:
            USER_URL: user:8080
        depends_on:
            - "user"
