// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isFilter_Value is an autogenerated mock type for the isFilter_Value type
type isFilter_Value struct {
	mock.Mock
}

// isFilter_Value provides a mock function with given fields:
func (_m *isFilter_Value) isFilter_Value() {
	_m.Called()
}

type mockConstructorTestingTnewIsFilter_Value interface {
	mock.TestingT
	Cleanup(func())
}

// newIsFilter_Value creates a new instance of isFilter_Value. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newIsFilter_Value(t mockConstructorTestingTnewIsFilter_Value) *isFilter_Value {
	mock := &isFilter_Value{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
