GRPC localhost:8080/test.elizabeth.acme.api.v1.UserService/CreateUser

{
	"first_name": "Elizabeth",
	"last_name": "Martin",
	"nickname": "elizabeth-dev",
	"password": "supersecurepassword",
	"email": "me@elizabeth.sh",
	"country": "ES"
}

###

GRPC localhost:8080/test.elizabeth.acme.api.v1.UserService/GetUsers

{
	"filters": [
		{
			"field": "nickname",
			"operator": "LESS_THAN",
			"string_value": "elizabeth-dev"
		}
	],
	"sort": [
		{
			"field": "created_at",
			"direction": "ASC"
		}
	],
	"pagination": {
		"limit": 0,
		"offset": 0
	}
}

###

GRPC localhost:8080/test.elizabeth.acme.api.v1.UserService/UpdateUser

{
	"id": "1cc41d24-1b9a-4042-82b9-5af83ff9a208",
	"nickname": "elizabeth-dev-2"
}

###

GRPC localhost:8080/test.elizabeth.acme.api.v1.UserService/RemoveUser

{
	"id": "1cc41d24-1b9a-4042-82b9-5af83ff9a208"
}
